### ISSUE TITLE
Full hud needs to push entire rendering screen up

### ISSUE THREAD

**Issue by nstlaurent** [Helion-Engine/Helion#376]
Currently only the gun is pushed up, but the original game rendered the entire screen pushed up by what looks like to be 16.

**Comment by Calinou** [comment]
Is this fixed by https://github.com/Helion-Engine/Helion/commit/33027b0d4be35fea478b8a94190943cb28a1457f?

**Comment by nstlaurent** [comment]
Yes, this has been completed.
