### ISSUE TITLE
Fatal error on startup

### ISSUE THREAD

**Issue by dfgdgdgfd** [Helion-Engine/Helion#524]
i3 5005u, intel hd 5500.  I tried to run this on a much older system at the request of one of the devs but wasn't able to, but expected it to run on a 2015 laptop with all windows 10 updates.

https://imgur.com/a/9GfjO1n

**Comment by nstlaurent** [comment]
Adding a note here for anyone else that might see this. The C++ redist was packaged into Windows updates at some point. If Windows isn't fully up to date or somehow missed it then the install needs to be done manually:

https://aka.ms/vs/17/release/vc_redist.x64.exe
