### ISSUE TITLE
Eviternity MAP26: rendering issues with invisible stairs

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#526]
Tested on master and eccd8e324e6ee32b227b51078aeefed765497062

It seems like the walls of invisible stairs on this map are fine, but the floors have a weirdness that causes voids.

Example 1 with Prboom+ comparison - the lower floor seems to be raised to the level of each step, leaving a void below

![floor](https://github.com/Helion-Engine/Helion/assets/115905880/27f4dc64-8cf8-439d-baf8-a9f2009398ad)

Example 2, the ledge and skybox get clipped

![helion_20230512_11 42 46 6012](https://github.com/Helion-Engine/Helion/assets/115905880/991531b2-2fa5-4ba4-9b22-963cd4deb86b)

Another angle

![helion_20230512_11 59 42 5841](https://github.com/Helion-Engine/Helion/assets/115905880/ab91e74f-e397-4073-81e9-397ccf3ece80)

I'm on Windows 10 with a 3060 Ti.

Also, great work on this engine! I love that I can finally run maps like this at 140fps. Some ports struggle and some have a playable framerate but still not 140. Uncapped I get almost 700 avg.

**Comment by nstlaurent** [comment]
As a note, this is a vanilla rendering hack that isn't supported yet. It's accomplished by setting both front and back sides to the same sector id that caused vanilla to not rendering if and flood the floor below.

**Comment by nstlaurent** [comment]
Fixed with 0.9.2.7
