### ISSUE TITLE
[Feature Request] Add Heretic, Hexen: Beyond Heretic (and Deathkings), and Strife: Veteran Edition Support

### ISSUE THREAD

**Issue by MasterO2** [Helion-Engine/Helion#530]
@nstlaurent 

Given that they are Doom-engine games, they should be supported in the future as well:

https://github.com/OpenSourcedGames/Hexen

https://github.com/OpenSourcedGames/Heretic

https://github.com/svkaiser/strife-ve

**Comment by lemming104** [comment]
Relatively unlikely in the foreseeable future.
