### ISSUE TITLE
Boom wall scroller discrepency

### ISSUE THREAD

**Issue by simc2** [Helion-Engine/Helion#538]
In Helion 0.9.2.2 and earlier.

Boom dynamic wall scrollers seem not to work quite as expected. That is the linetypes 249 Scroll and 218 Accelerate wall when the control sector changes height. Here's a test wad for Doom2 map01
[249scrollers.zip](https://github.com/Helion-Engine/Helion/files/13404758/249scrollers.zip)

On the west side room there are three combos of a switch, a lift with the 249 scroller and the scrolled wall. Those three systems are only rotated 45 and 90 degrees to each other and they all should scroll ~identically.

On the eastern room there's one switch and three lifts with scrollers. The scroller lines are in 45 degree angles to each other and each of them scroll two slightly tilted walls. In Boom all the scrolled walls should go to the different directions. In Helion the resut resembles more like MBF21's 1025 and 1026 offset scrollers.

**Comment by nstlaurent** [comment]
Thanks for the example! I have it fixed for the next release.
