### ISSUE TITLE
libfluidsynth.so not found when libfluidsynth is installed (Linux Mint 21.2)

### ISSUE THREAD

**Issue by EClaus-doom** [Helion-Engine/Helion#539]
On Linux Mint 21.2 Helion is unable to locate libfluidsynth.so even when installed, Linux Mint 21.2 has libfluidsynth.so.3.0.5 and a symlink libfluidsynth.so.3 which it appears Helion isn't looking for. I was able to do a workaround where I made another symlink in the same folder that was just libfluidsynth.so (not sure why Mint doesn't have one). Helion might just need to be updated to search for a few more potential wild cards of this library name for execution, but it did work after I made the symlink myself so it's looking in the proper directories. While this solution works it might be a bit harder to understand for more novice Linux users, but it should work on other distros with the same issue. I included my errorlog so the specific wording of the error is present.
[errorlog.txt](https://github.com/Helion-Engine/Helion/files/13470515/errorlog.txt)

**Comment by EClaus-doom** [comment]
To clarify this is with the current Linux build.

**Comment by nstlaurent** [comment]
Fixed with 0.9.2.4
