### ISSUE TITLE
When I restart Helion some values change to random numbers

### ISSUE THREAD

**Issue by franzmondlichtmann** [Helion-Engine/Helion#545]
When I restart Helion some values change to random numbers. For example the sound pitch went from 1 to 10, and the mouse sentivity from default to 500 and playback speed from 10 to 100 (it was definitively 10 before). And it changed multiple times, each restart.

Windows 11
Helion 0.9.2.6 x64 with Runtime
Tested in Doomrunner (Launcher) and UDB.

**Comment by nstlaurent** [comment]
Can you attach your config.ini file? And you are using the (DEU) German keyboard layout too, correct? Just in case that last part matters.

**Comment by franzmondlichtmann** [comment]
> Can you attach your config.ini file? And you are using the (DEU) German keyboard layout too, correct? Just in case that last part matters.

Yes correct im using the german (Deutschland) Windows 11 Layout.
I made a copy of the ini and made it a txt file, so I can upload it on github. (Just if you are wondering). 
[config.txt](https://github.com/Helion-Engine/Helion/files/13706795/config.txt)

**Comment by nstlaurent** [comment]
I think I know what the problem is. It is reading your culture info and the decimal separator is a comma. If you enter a decimal in the English format like 10.0 instead of 10,0 then it gets parsed to 100. I will update Helion for the next release to correctly show default numbers with the correct separator.

**Comment by franzmondlichtmann** [comment]
I will test it thourougly, but the change with the comma seems already promising.
I might close, if this error does not happen while playtesting.
