### ISSUE TITLE
Player Viewangle / Height seems off in Helion compared to other sourceports?

### ISSUE THREAD

**Issue by SharlLegreg** [Helion-Engine/Helion#548]
Running Helion 0.9.2.5

It seems that the player view elevation / height is higher compared to other sourceports. This does not affect projectiles trajectory but it is still jarring to look at. Mouselook is disabled for all screenshots.

Below is a comparison

( Helion 0.9.2.5, take note of where the pistol sight is aiming at the torso of the zombieman )
![helion_20231220_11 27 41 6119](https://github.com/Helion-Engine/Helion/assets/63714563/39e70fb8-1e07-4d90-b2a6-4db6bd376543)

( GZDoom 4.10 using OpenGL renderer , the pistol is now aiming at the floor next to the zombieman )
![Screenshot_Doom_20231220_231725](https://github.com/Helion-Engine/Helion/assets/63714563/2219d4f7-f031-4484-986e-99da80d7f361)

( PrBoom+ 2.5.1.4 using OpenGL renderer )
![doom00](https://github.com/Helion-Engine/Helion/assets/63714563/8b71286d-711a-44c3-9753-ad55ba2337cf)

( Control, Chocolate Doom 3.0, the pistol is aiming at the floor next to the zombieman foot instead of near the torso )
![image](https://github.com/Helion-Engine/Helion/assets/63714563/4f56acf8-d971-486e-aa05-ae6496bad764)

I'm not sure what causes this but it definitely feels off and very noticeable.

**Comment by nstlaurent** [comment]
This is because Helion doesn't support changing the viewport when using the full size hud. The gun is pushed up to compensate for this. It will look normal if you use the minimal hud. You can also push the gun down by going to Options -> Hud and setting Full Size Bar Gun Offset to 0 if you want to keep the fullsize hud.

**Comment by Calinou** [comment]
There's an existing issue on this: https://github.com/Helion-Engine/Helion/issues/376

**Comment by SharlLegreg** [comment]
This issue seems to be fixed on the latest 0.9.2.7 release. I'm closing this issue.
![helion_20240319_11 33 49 9292](https://github.com/Helion-Engine/Helion/assets/63714563/b032c783-38da-4449-a84d-71f73c69b154)
