### ISSUE TITLE
Fullscreen HUD doesn't use 1.2× vertical 2D scaling like the status bar

### ISSUE THREAD

**Issue by Calinou** [Helion-Engine/Helion#552]
**Helion version:** https://github.com/Helion-Engine/Helion/commit/3e60de303e27c74738b6e98e125ffb48a552c2cd

Notice how the text and mugshot are vertically squashed on the fullscreen HUD compared to the status bar.

### Status bar

![image](https://github.com/Helion-Engine/Helion/assets/180032/4c9edd3c-4661-4a57-94e3-b19c1f816855)

### Fullscreen HUD

![image](https://github.com/Helion-Engine/Helion/assets/180032/2fe61157-5d00-421e-bf6f-200708f1f7fe)

Pixel-perfect 2D scaling can only be achieved by a 2D scale factor of 5× (so each 5×5 square becomes 5×6), so this may have to be optional as it may not look great at scale factors between 1× and 3×.

**Comment by nstlaurent** [comment]
Is the problem that the first screenshot is rendering the sprites differently compared to the second? I don't understand the last statement about pixel-perfect 2D scaling if you could clarify, thanks :)

**Comment by Calinou** [comment]
> Is the problem that the first screenshot is rendering the sprites differently compared to the second?

The first screenshot is correct, the second screenshot is wrong (compared to the expected appearance).

> I don't understand the last statement about pixel-perfect 2D scaling if you could clarify, thanks :)

See https://zdoom.org/wiki/Aspect_ratio_correction. The vertical scale factor is 1.2×, so you need a scale factor of 5×[^1] to be able to represent it without any uneven pixel scaling (i.e. *each* pixel that is 5×5 pixels becomes 5×6). Otherwise, some rows of pixels will be 1 pixel taller than others. It's a similar problem to [integer scaling](https://tanalin.com/en/articles/integer-scaling/) but with a larger multiplier.

[^1]: Multiples of 5× will also work, though 10× is too large even on a 4K display.

**Comment by nstlaurent** [comment]
Thanks, I just wanted to be sure. Funny enough, Odamex does the same thing between the full and minimal HUD and I never noticed it there either.

I fixed the sprites for the minimal HUD so they render to match the full sized HUD.

![screenshot_Helion Debug_DOOM](https://github.com/Helion-Engine/Helion/assets/42744211/d8c533b7-fd63-419e-b9aa-e2b21468274c)

**Comment by Calinou** [comment]
> I fixed the sprites for the minimal HUD so they render to match the full sized HUD.

Looks good, could you also apply this to the HUD font? It still seems squashed as far as I can tell.

**Comment by nstlaurent** [comment]
Thought that was going to be more difficult. Ended up being easy so that is done as well.

![screenshot_Helion Debug_DOOM](https://github.com/Helion-Engine/Helion/assets/42744211/5c9e9032-1b7b-48f4-916e-27e8aebfea9b)

**Comment by Calinou** [comment]
Looks great! I think all that's missing now is the console text at the top (also in the options menus), but this may be more involved and may not look great at low scale factors. Some source ports allow configuring text scaling independently from the HUD for this reason.

**Comment by nstlaurent** [comment]
Completed.
