### ISSUE TITLE
No sound ingame: Cannot convert from mus to midi.

### ISSUE THREAD

**Issue by franzmondlichtmann** [Helion-Engine/Helion#553]
Lastest git version of helion, tested on WIN11 and OpenSuse Tumbleweed.
Sound in the menu works, but sound in the game does not work.
Following error occurs:
"Cannot convert from mus to midi."

Also:
Merry christmas!

**Comment by nstlaurent** [comment]
Merry Christmas!

Is this a specific map or always? Helion currently only supports midi and mus files. Since mus files don't have a header it will stupidly assume it's a mus file if it encounters something it doesn't support like an mp3 or ogg.

**Comment by franzmondlichtmann** [comment]
The problem happens with the map ancient aliens. [https://doomwiki.org/wiki/Ancient_Aliens]()
[https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/aaliens]()
Helion works fine on many other maps though.

**Comment by nstlaurent** [comment]
It's because the first map is an ogg. I'm working on getting ogg/mp3 support.

**Comment by nstlaurent** [comment]
I pushed what I have to dev, feel free to try it out. May not to be the most stable until I have time to test after Christmas :)

**Comment by franzmondlichtmann** [comment]
Thanks man, enjoy christmas :)

**Comment by nstlaurent** [comment]
Fixed with 0.9.2.7
