### ISSUE TITLE
Audio volume setting is incorrectly displayed when loading settings

### ISSUE THREAD

**Issue by Calinou** [Helion-Engine/Helion#556]
**OS:** Linux
**Helion version:** https://github.com/Helion-Engine/Helion/commit/45139afec7bd0477fb0922bda8e8cf34c815de14

If you set the audio volume to `0.35`, it will initially appear correctly, but once you restart the game, it'll look like this:

![Screenshot_20240108_222059](https://github.com/Helion-Engine/Helion/assets/180032/9a42b2f7-b730-4b79-9b21-f5cd9714f6e3)

The configuration file written after the game exits appears to be fine:

```ini
[engine]
audio.musicvolume = 0.0
audio.soundvolume = 0.035
```

This is likely a floating-precision error when converting the value for editing (since it appears to be multiplied by 10).

**Comment by 72hr** [comment]
Does this still occur in 0.9.4? It looks OK to me, but I'm on Windows.

**Comment by 72hr** [comment]
I looked into this a little more, this was fixed in version 0.9.2.9.
