### ISSUE TITLE
Freelook gets gradually less precise the higher/lower you look at

### ISSUE THREAD

**Issue by Calinou** [Helion-Engine/Helion#557]
**OS:** Linux
**Helion version:** https://github.com/Helion-Engine/Helion/commit/45139afec7bd0477fb0922bda8e8cf34c815de14

The higher/lower your pitch is, the less precise freelook will be. This results in visible snapping of the horizontal angles you can look at.

In this video, I move the mouse in a stable line at a mostly constant speed. The mouse will appear to jitter when fully looking upwards, but I'm not actually shaking the mouse. The issue is more noticeable in fullscreen.

https://github.com/Helion-Engine/Helion/assets/180032/5d34dafb-f7be-4a53-bedd-776ba0a103e5

**Comment by 72hr** [comment]
Looks like this one got fixed in 0.9.3.0.
