### ISSUE TITLE
shader issue

### ISSUE THREAD

**Issue by JimFlasch** [Helion-Engine/Helion#558]
I tried to run the latest version of Helion in Windows 10, and it crashed back to desktop. The error log led off with the following:

02:26:58.7634 Fatal error occurred System.Exception: Error linking render shader: The fragment shader uses varying distanceOffsetFrag, but previous shader does not write to it.

The whole file  (just a traceback of the error to its originating point) is attached. I have the .NET 7.0 desktop runtime installed, BTW.

[errorlog.txt](https://github.com/Helion-Engine/Helion/files/13884405/errorlog.txt)

**Comment by nstlaurent** [comment]
I'm going to guess this is an Intel GPU? It does expose a problem that the AMD and Nvidia GPUs I have are ignoring. This build should hopefully resolve it:
[Helion 0.9.2.7](https://www.dropbox.com/scl/fi/vjxah43vy5u2fw49goif9/Helion-0.9.2.7-win-x64-with-Runtime.zip?rlkey=l4louks8m3941b6c5uxd0s4ok&dl=0)

**Comment by JimFlasch** [comment]
Thanks - works now.
