### ISSUE TITLE
MBF21 Gameplay Mods Graphical Issues

### ISSUE THREAD

**Issue by SadCack** [Helion-Engine/Helion#559]
There are several issues I have encountered when attempting to use MBF21 compatible gameplay mods. When using "Supercharged Bullet Ride", various enemy corpse sprites pop out of damaged enemies when whey are hit. There are different sprites for each weapon, such as the SMG creating Mancubus corpses and the shotgun creating Imp corpses. 
When using the "Minicharged" mod, the minigun sprite disappears when firing and only reappears when the weapon is switched. Both of these mods function correctly in engines such as DSDA and Nugget-Doom, so the issue appears to be with the engine.

**Comment by nstlaurent** [comment]
Fixed with 0.9.2.8 release
