### ISSUE TITLE
Arch-Vile flame may not properly render infront of the player if the Arch-Vile is behind the player or if the player quickly turns away at the start of the attack

### ISSUE THREAD

**Issue by SharlLegreg** [Helion-Engine/Helion#561]
OS: Windows 11 23H2
Version Tested: https://github.com/Helion-Engine/Helion/commit/9641031c8470d6843b37516e8807494062f617f0

Basically title. The video below demonstrates the issue. This issue become more consistent the further the player is from the Arch Vile; and possibly related to FOV as higher FOV tends to make the issue less consistent, but I couldn't conclusively prove it. This issue failed to be replicated on other sourceports ( Tested on DSDA-Doom 0.27.5 and GZDoom 4.11.3a )

https://www.youtube.com/watch?v=3lKaWyRnXjM

**Comment by nstlaurent** [comment]
Fixed with [1faa92e](https://github.com/Helion-Engine/Helion/commit/1faa92ec2b1c3350578086410348eafe64d9bde4)
