### ISSUE TITLE
[Feature Request] add -savedir arg

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#563]
GZDoom has a `-savedir` arg to specify where save games are stored, similarly DSDA has a `-save` arg. I like to use this in tandem with a launcher to keep save games next to WADs.

I gave it a shot, if this is in scope: https://github.com/72hr/Helion/tree/savedir, I don't love storing the save dir in SaveGame but I couldn't think of a good way to avoid it without moving parts of the loading/saving code into SaveGameManager

**Comment by nstlaurent** [comment]
It looks ok to me. You can make a pull request for this. The only thing I would say is that the SaveGameManager should take the save directory as a parameter instead of CommandLineArgs.
