### ISSUE TITLE
Improved crosshair

### ISSUE THREAD

**Issue by piXelicidio** [Helion-Engine/Helion#565]
First I want to congratulate you for the awesome project, runs great, nice features and is in C# (as I was looking for).

 I wish to have a less "intrusive" crosshair that doesn't obstruct the pixels right in the center of the screen.

I felt brave enough to sniff in the code :) and found the DrawCrosshair method, where I modified it to draw four smaller segments at the ends of the cross. Also set alpha to 0.5f.

Maybe you like this better, or could be optional somehow:

```
       var lengthFraction = totalCrosshairLength / 4;
        hud.FillBox((horizontal.X, horizontal.Y, horizontal.X + lengthFraction, horizontal.Y + HalfWidth), color, alpha: 0.5f);
        hud.FillBox((horizontal.X + totalCrosshairLength - lengthFraction, horizontal.Y, horizontal.X + totalCrosshairLength, horizontal.Y + HalfWidth), color, alpha: 0.5f);
        hud.FillBox((vertical.X, vertical.Y, vertical.X + HalfWidth, vertical.Y + lengthFraction), color, alpha: 0.5f);        
        hud.FillBox((vertical.X, vertical.Y + totalCrosshairLength - lengthFraction, vertical.X + HalfWidth, vertical.Y + totalCrosshairLength), color, alpha: 0.5f);
```
![image](https://github.com/Helion-Engine/Helion/assets/6601446/991e762d-974e-4740-aedd-023bc62f6128)
![image](https://github.com/Helion-Engine/Helion/assets/6601446/badf416b-7351-46a2-909e-5937acad0e0f)

**Comment by nstlaurent** [comment]
Thanks! I'm glad you felt brave enough to try this. I do like that crosshair better. I can add it as an option along with transparency and scaling.

**Comment by nstlaurent** [comment]
This has been implemented with configurable types, colors, and transparency in the options.
