### ISSUE TITLE
Intermission background image scale issue

### ISSUE THREAD

**Issue by piXelicidio** [Helion-Engine/Helion#566]
Found after finishing map06 Doom II, the resolution of the background is too high compared to text, looking unpleasant. Second image from GZDoom for comparison:

![image](https://github.com/Helion-Engine/Helion/assets/6601446/f5505490-cefe-4c72-a353-fb59045a17f2)

![image](https://github.com/Helion-Engine/Helion/assets/6601446/d6f5cc14-fbae-43cd-bfff-8fc13c91d8dd)

**Comment by 72hr** [comment]
Seems to be fixed in current versions? 1920x1080:

![](https://github.com/user-attachments/assets/f710f2fe-5560-4ae3-bc68-92741da6ab7d)

**Comment by lemming104** [comment]
Yeah, this does not seem to repro anymore.  I tried both full screen and windowed, messed with the HUD scale just in case, etc.
