### ISSUE TITLE
Reveled all map by powerup drawn "incorrectly"?

### ISSUE THREAD

**Issue by piXelicidio** [Helion-Engine/Helion#567]
When getting the Computer map power up the automap is drawn like this with double-sided lines in gray, same as when are seen, that make it confusing to understand what was reveled. (Replaced LightBlue for Blue for debugging and personal preference).

![fix_Clipboard_04-25-2024_02](https://github.com/Helion-Engine/Helion/assets/6601446/1801aa24-03da-4fc6-b427-e03276210afd)

This is how the map is reveled in Chocolate:
![image](https://github.com/Helion-Engine/Helion/assets/6601446/297b48c9-a78a-4c2e-87b7-2104eba23ab4)

Tried to do a fix here https://github.com/Helion-Engine/Helion/commit/8ad08bed838935c31bea4bcd94f929985080a59e

Resulting in:
![fix_Clipboard_04-25-2024_01](https://github.com/Helion-Engine/Helion/assets/6601446/efeb00ad-d5ae-4b53-a545-9c39706f5016)

I'm totally noob at contributing in Github (Made a PR once long time ago, can't remember how :D ), and I'm not even sure if this kind of very small fixes will actually help you or create just noise in your workflow. Also the code complexity is way over my C# level. I'm just doing a full playthrough of Doom 2 using Helion (currently at level 20) and It's been fun for me to test things, modify and try to understand and learn from your code.

**Comment by nstlaurent** [comment]
I added the two-sided line color fix on dev. Thanks!
