### ISSUE TITLE
[Linux/Ubuntu] Stock instructions need updating for .NET 8

### ISSUE THREAD

**Issue by MartinHowe426** [Helion-Engine/Helion#568]
On a fresh install of Linux Mint, followed the instructions in the Readme. All is well until I try to run the build script; then the error "./Scripts/build.sh: line 3: dotnet: command not found" occurs. This can be fixed by installing dotnet7 from the apt package manager; but that fails with a compiler error on the new _collection expressions_ feature. Building with .NET 8 and its SDK fixes the problem and it doesn't seem to need **dotnet8** be installed explicitly.

So please can the build instructions for Ubuntu be updated accordingly?

sudo apt install dotnet-sdk-**8**.0 libfluidsynth-dev libopenal-dev

**Comment by nstlaurent** [comment]
Updated readme, thanks.
