### ISSUE TITLE
Persist "fast monsters" behavior in savegames

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#573]
The value of the "fast monsters" setting in the General section is not persisted to the config file.  This actually makes sense, because starting a new game and _not_ realizing that you've enabled the setting is pretty unpleasant.

However, it's not persisted in savegames either.  If you quit out of the game, start it up again, and load a savegame that was begun with fast monsters, the monsters are back to "normal" reaction times.  This can be remedied by going into the settings menu, enabling fast monsters, and reloading the savegame yet again.

Would it be possible to persist this value in savegames?  It's a pretty significant difficulty modifier, so it seems almost as important as the "base" difficulty setting.

**Comment by nstlaurent** [comment]
Fixed on dev. Both fast monsters and no monsters will be serialized to the save.
