### ISSUE TITLE
Commit 60da844 introduces rendering glitches

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#574]
The changes introduced by commit 60da84494e9e9f89acfbee34955d77c47b545e9a cause some strange rendering defects on doors and elevators.

This can be easily seen on E1M1 of Doom.  Just open the first door on the main path through the level.

1.  It no longer appears to animate smoothly.  Did this change break interpolation?
2.  Watch either the right or left edge of the door as it opens, and observe the wall texture in the "door track".  It appears to shake up and down as the door opens or closes.  This effect is also noticeable on some larger elevators and stuff.

I've attached two pictures of the phenomenon I am describing in point 2.  If you flip back and forth between them, you can see the texture jiggle.

![helion_20240517_03 48 57 4496](https://github.com/Helion-Engine/Helion/assets/50272946/251e693d-5cad-42ce-acbc-9b5677e8799f)
![helion_20240517_03 48 57 5988](https://github.com/Helion-Engine/Helion/assets/50272946/3646238a-29a3-4724-bc73-5cdeb84ed060)

**Comment by nstlaurent** [comment]
I was working on it as you were typing this up. Got a little push happy today. Should be fixed with the latest push.

**Comment by lemming104** [comment]
Cool, didn't know whether you'd noticed it yet and thought it was best to point it out before it got buried under other commits.  :)

**Comment by lemming104** [comment]
Yes, appears to be fixed in d1f619be73d508a198d9f1224f7e46aa1ab82efc.
