### ISSUE TITLE
Badly bugged teleporter destinations

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#575]
I'm not 100% sure, but I think this is some state that isn't getting cleared when the user changes difficulty.  Here are the most repeatable repro steps I have been able to come up with.

I am on my own private build, based on GIT SHA 3dc7e42663d4cfdd797b50d0c66540ef1bee6e8c.  I have no local changes.

1.  Launch Helion, using the Doom2 1.9 WAD (CRC32: EC8725DB)
2.  Start a new game on the lowest difficulty setting
3.  Pull down the console, type `map map23`
4.  Escape the big hallway you start out in, open the door at the end, and go through the teleporter.

Expected/Actual:  You are teleported to the coordinates shown in the screenshot below, and can continue playing.
![helion_20240518_10 21 32 6336](https://github.com/Helion-Engine/Helion/assets/50272946/69ecf30a-e238-4124-aa55-c0819bd3c2dd)

5. ***WITHOUT QUITTING HELION***, open up the menu and start a new game on Ultra-Violence difficulty
6.  Go into the console, type `map map23`
7.  Again, escape the big hallway and step onto the teleporter.

Expected:  You should be teleported to the same coordinates as in the first game.
Actual: You are teleported directly on top of a barrel and have a very, very bad day:

![helion_20240518_10 23 00 9927](https://github.com/Helion-Engine/Helion/assets/50272946/03765393-e394-4815-9036-18254ab62644)

**Comment by nstlaurent** [comment]
Good catch. This dev build of Helion currently reuses a lot of these objects in an effort to reduce map load times for the same map when the player dies or is loading a save. The teleport spots are stored separately and weren't being cleared. Should be fixed with [this commit](https://github.com/Helion-Engine/Helion/commit/c2c095c1a2d9ad5d210b14a324a23b2c39c63f28)

**Comment by lemming104** [comment]
Always nice when the fix is just a one-liner!
