### ISSUE TITLE
Regression: switches no longer work in KDIKDIZD

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#577]
This is a recent regression and was introduced in the last day or two (we are at commit 504fc4d as of this writing).   I have not bisected to find the commit responsible, but I can do so if needed.

In KDIKDIZD (https://www.doomworld.com/idgames/levels/doom2/megawads/kdikdizd), some of the switches no longer work.

Repro steps:  Load the PWADs in that archive on top of a Doom2 IWAD, and start a new game on any difficulty setting.  Wander through the various open doors, until you come to a switch (coordinates shown in screenshot below). 

Expected:  Activating the switch should open a nearby door.  You should also see the door opening on a security camera view next to the switch.
Actual:  The door does not open.

The switch (coordinates in upper right):
![helion_20240523_09 24 32 5917](https://github.com/Helion-Engine/Helion/assets/50272946/0c620f7b-5970-4f69-a172-bff9b36cc2fd)

The door it is supposed to open:
![helion_20240523_09 24 42 2613](https://github.com/Helion-Engine/Helion/assets/50272946/42cab4d7-7db9-4b45-b248-a65c6dbfdbaf)

**Comment by nstlaurent** [comment]
Looking into this showed that infinitely tall things wasn't being set from the complvl lump setting vanilla. For some reason the changes introduced require this to be set for KDIKDIZD scripts to work when it wasn't required before. I fixed setting infinitely tall things with the vanilla complvl which fixes this issue. I'm still going to dig some more to see why the physics are working differently here with infinitely tall things off.

**Comment by nstlaurent** [comment]
Fixed with 0.9.3.0
