### ISSUE TITLE
DBP66 (RC1): MAP01 Monster does not teleport in

### ISSUE THREAD

**Issue by franzmondlichtmann** [Helion-Engine/Helion#583]
Download link: https://www.doomworld.com/forum/topic/145986-dbp66-lunar-strain/
- used the latest Helion which I build myself against arch linux
***********************************************************************************************
The monster in the last room before the exit on MAP01 does not teleport in, why that is I'm not completely sure.
It works with the Doom Source Port Woof though.
You can just open the map in Ultimate Doom Builder and search for the tags.
- It will show that the teleport destination sector of the monster has tag 30 and uses 126 (WR) Teleport Monsters.
- Its triggered by linedef tag 29 and uses 109 Door Open Stay (fast).

![image](https://github.com/Helion-Engine/Helion/assets/105480088/a6b3b443-a5ec-473f-8c4e-59debf4d4688)

**Comment by nstlaurent** [comment]
Fixed for next release.
