### ISSUE TITLE
Partial invisibility effect "darker" for HUD weapons than for spectres

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#586]
I am not 100% sure whether this is a bug or an intentional change.  

The current dev branch code causes HUD weapons to appear darker than partially-invisible monsters like spectres.  (Additionally, there is a longstanding behavior where the chaingun and pistol show a "layering" effect when firing; this has been around for as long as I can remember.)

Here's how partial invisibility looks in the last release (0.9.3.0); spectres and player HUD weapons appear to have similar darkness:
![0 9 3 0_invislayering](https://github.com/user-attachments/assets/7f852a11-b20e-4aa3-887b-24ad341abea0)

Here's how it looks in https://github.com/Helion-Engine/Helion/commit/b37180942158eeb903bf4b9d83cd6d2b22040c77, in truecolor mode:
![WIP_truecolor](https://github.com/user-attachments/assets/a19eb138-8fbc-45fe-aa94-a665e21af047)

And again, in palette mode:
![WIP_colormap](https://github.com/user-attachments/assets/e8d7f9cd-d1ea-47ac-a508-e8fa5d4644ee)

In both of those, HUD weapons are noticeably darker than spectres.

For comparison, here's a similar scene in DSDA-Doom:

![doom02](https://github.com/user-attachments/assets/69d2ff24-1703-4315-9ad4-e8b01b6596ca)

**Comment by nstlaurent** [comment]
The weapon drawing darker should be fixed now. The Sprite overlap for certain weapon firing is going take a bit of work.

**Comment by lemming104** [comment]
Confirmed that 11ca1a9c04994dc5ddaafe32d11cbbab412f8815 fixes the primary issue here.
