### ISSUE TITLE
Rendering artifacts when looking up or down at steep angles

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#587]
This one's pretty simple; load up any level of any IWAD, and look straight up or down.  Seems to be a regression since 0.9.3.0 and occurs regardless of color mode or "vanilla sprite rendering" options.

![helion_20240804_06 23 45 1801](https://github.com/user-attachments/assets/474c23e3-cbe5-4424-ae6f-05da1f99c677)

If you're outdoors and look straight up, you can still see part of the skybox, although the rest of the textures and such are all missing.
![helion_20240804_06 28 13 1163](https://github.com/user-attachments/assets/99cda7cc-9821-4eb0-a4cd-3e357db33abb)

**Comment by nstlaurent** [comment]
This should be fixed now, thanks!

**Comment by lemming104** [comment]
Confirmed that 74694ca5eea1f6258e246e1e4f6dec10456e56b8 fixes this issue.
