### ISSUE TITLE
Automap overlay layering -- should automap render over HUD weapons?

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#590]
The automap overlay and rotation features are great and are a _huge_ help when navigating complex maps, but it seems odd to me that the overlay renders _under_ HUD weapons, especially when rotation is enabled.  Should it render over these instead?  What about the status bar?

This just feels kinda weird to me:
![helion_20240806_10 06 41 3067](https://github.com/user-attachments/assets/8b0d2287-9041-4b86-995e-84ef14288d97)

**Comment by nstlaurent** [comment]
Yeah it's a problem. I looked into it and don't entirely understand why but all hud elements are drawn over everything which includes the automap regardless of order. I decided to push off looking into this problem, we can leave this open as a reminder of the issue.

**Comment by nstlaurent** [comment]
Did some testing with the latest rendering changes on various hardware and found something interesting. The laptop with the AMD HD8400 renders the automap correctly for some reason, and it's the only one. The weapon draws over the automap on my RTX 3070, AMD Vega (Ryzen), and Intel UHD 630.

![hd8400](https://github.com/user-attachments/assets/6cac390a-d338-4971-9816-1033b6871d4a)

**Comment by lemming104** [comment]
If I had to guess which one of those machines would actually render the automap correctly, that would not have been it.  I would have guessed the Intel HD one, just because their drivers always seem to have bugs that the Nvidia and AMD stuff doesn't.  😆

**Comment by nstlaurent** [comment]
This should be fixed now that I figured out what was going on. How that AMD rendered it 'correctly' is beyond me, but it's obviously wrong lol...

I also added options to set a backdrop color and transparency with some defaults. I'm open to suggestions on defaults, for me the overlay automap becomes hard to read some some noisy maps and the backdrop helps a lot for me.

**Comment by lemming104** [comment]
As of 4e6540bf549e0ec7f151c0e28dba50e284b9102c, this seems to work as expected on my machine.

The black 70% transparent background seems like a totally reasonable default to me.
