### ISSUE TITLE
Make pressing Escape close the console

### ISSUE THREAD

**Issue by Calinou** [Helion-Engine/Helion#591]
In other source ports such as GZDoom, pressing <kbd>Escape</kbd> closes the console (regardless of bindings), but it does nothing in Helion. This breaks my muscle memory, so I'd like <kbd>Escape</kbd> to act the same in Helion (even if the console toggle remains bound to <kbd>Backtick</kbd>).

**Comment by nstlaurent** [comment]
This is done on dev and will be out in the next release :)

**Comment by Calinou** [comment]
For future reference, this was implemented in https://github.com/Helion-Engine/Helion/commit/74fe1c62693b49ecf4d30f2d6b931e2167d5fb2b.
