### ISSUE TITLE
BTSX E2 level 15 to 16 refuses to load

### ISSUE THREAD

**Issue by syyyynapse** [Helion-Engine/Helion#596]
Was doing a play through of BTSXE2, finished level 15, intermission screen showed up, then console showed up giving me this error:

![image](https://github.com/user-attachments/assets/37f62fba-c348-42df-96bd-3aaab76be7c7)

IDCLEVing directly to map 16 loaded it just fine, something about going from map 15 to 16 is causing issues. Not sure what. Doesn't ruin my play through but I hope whatever causes this gets patched soon.

**Comment by nstlaurent** [comment]
So it appears that there are two maps (MAP16 and MAP16C). MAP16C is next map from 15 defined in ZMAPINFO and it always fails because zdbsp puts the marker as GL_MAP16 instead of GL_MAP16C that Helion is looking for. I will put in a fix for the next release that should go out this weekend.

**Comment by nstlaurent** [comment]
This is fixed [here](https://github.com/Helion-Engine/Helion/commit/b627d0db692094ec1d992589dcc053779f0474b8) and will be out with the next release.
