### ISSUE TITLE
[Feature Request] XInput Support

### ISSUE THREAD

**Issue by Darthtallgeese** [Helion-Engine/Helion#602]
Any plans to add support for controller in near future?

Been playing Doom with controller since SNES.

**Comment by nstlaurent** [comment]
Controller support will happen. Working on the new ID24 spec so I can look into it after that.

**Comment by lemming104** [comment]
It looks like there's _supposed_ to be cross-platform controller support baked into OpenTK, so that's cool.

**Comment by Darthtallgeese** [comment]
> Controller support will happen.

That's good news 👍

Proposing a feature is easy, implementing it is another thing.

![W-Toggle](https://github.com/user-attachments/assets/bf36e411-da1b-4860-a270-e3ffaf531662)

**Comment by lemming104** [comment]
I'll at least do some initial investigation here.

**Comment by lemming104** [comment]
There is an initial implementation of controller support in the dev branch now, and it will be included in the 0.9.5.0 release.

**Comment by Darthtallgeese** [comment]
Great news!
