### ISSUE TITLE
Ancient Aliens: bottom of message text font is cut off

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#612]
On 36a04d1bb0a75031601983f22112f7a1cf03a19a with AA 1.3 from https://www.doomworld.com/profile/8877-skillsaw/?status=1747176&type=status

Seems to be 3 pixels:

![text-clipping-helion](https://github.com/user-attachments/assets/71fe6b9f-5998-4392-924f-73abe9dc9e43)

compare DSDA:

![text-clipping-dsda](https://github.com/user-attachments/assets/f6905736-a3b7-4fd5-ac64-5f4efcd8ed7e)

This also happens with 1.0 and 1.2.

**Comment by lemming104** [comment]
This one's definitely been around for a while.  I wonder if that font is taller than the original Doom one and Helion's code just assumes that they are the same height.

**Comment by 72hr** [comment]
I looked into it some more and the SmallFont glyphs are all 10px tall, instead of the default 7. In the code the maxHeight gets changed to the default height instead of the measured maxHeight, so it will never load the last 3 pixels of those glyphs, but I found I could do so with these changes:

![image](https://github.com/user-attachments/assets/65f246bf-0110-4afd-85c3-e07503e17551)

While it now displays OK, that does some undesirable things:

- the message size is based off a fixed height, so taller fonts will be narrower to fit, and be noticeably smaller for hud messages, which are already IMO too small (this screenshot is hudscale 2x)
- the statusbar text is now too large and positioned incorrectly (see the 105%)
- in some text screens the text goes off the screen (is the line height non-fixed here?)

![text1](https://github.com/user-attachments/assets/d18e0c92-5365-49e5-8a19-262a02eddfbd)

![text2](https://github.com/user-attachments/assets/46f447a2-a1cb-42c9-b005-19a997b6aba0)

compare DSDA, which also clips a little on the right:

![text-dsda](https://github.com/user-attachments/assets/5d087784-37e5-40d1-a602-4546203c210b)

so I need to do some more research here.

**Comment by 72hr** [comment]
I made some changes, but I'm not sure if they're ready.

https://github.com/Helion-Engine/Helion/compare/dev...72hr:font-fixes

This allows reading full glyphs when their height exceeds the defined fixedheight from Fonts.txt.

Since the atlas height now exceeds the defined height, the defined height now takes precedence when drawing, to prevent shrinking fonts whose glyphs are taller (matching other ports like DSDA/GZDoom).

But, it feels like that might be going against the original intention of fixedheight. What do you think, @nstlaurent?

Before/afters:

![4-before](https://github.com/user-attachments/assets/29061d1f-189b-47d7-ba1f-e713207267d3)
![4-after](https://github.com/user-attachments/assets/ffa4ce1f-ca8e-4028-8c23-a3e2c05ff65a)
![1-before](https://github.com/user-attachments/assets/37302d28-c4ad-45c2-bc36-4a80a35ec5f4)
![1-after](https://github.com/user-attachments/assets/64f947a1-293e-4718-b317-fa824c96dfe9)
![2-before](https://github.com/user-attachments/assets/7b84dfe7-593c-4448-b0fe-f7b183858774)
![2-after](https://github.com/user-attachments/assets/c80f6492-285d-4b4b-86da-3e231f9f4bd2)

**Comment by nstlaurent** [comment]
This is nice work. I have some test wads that have given me font rendering issues in the past so I will run it against those too. If the fixedheight needs to go away that is an option too, it seems that I misinterpreted that Doom rendered them at a fixedheight. It was pretty recently that I learned the large hud font was based off the width of the 0 char image.

**Comment by lemming104** [comment]
There's probably some secondary stuff we will need to do with the menus once this is in, since the options menus also use the smallfont.  I kind of want to make a pass through that stuff anyway, because there's some stuff that frequently runs off the screen even at reasonable scales.

**Comment by 72hr** [comment]
It didn't feel right to treat fixedHeight as a baseHeight, so I gave it another go, this time adding a baseHeight, which is used for alignment when generating the glyphs (e.g. so that periods draw at baseline instead of the actual bottom). I'm curious how vanilla does it, since the period glyph is just 4x4.

Then, fixedHeight functions as it used to (glyphs will be cut off if taller). And in places where we're drawing bitmap fonts I changed it to draw at the font's MaxHeight, so it's basically just drawing 1:1 onto the virtual dimension. This also fixes the intermission text being too small in Ancient Aliens.

https://github.com/Helion-Engine/Helion/compare/dev...72hr:font-fixes-2

![intermission-before](https://github.com/user-attachments/assets/0525ca17-708b-484a-a931-9b5f39a85f37)
![intermission-after](https://github.com/user-attachments/assets/37b01348-ced0-4cb9-a173-860b93fcfa4e)

**Comment by nstlaurent** [comment]
I was thinking something like this was the answer. Looking at the source it does seem to have some hard-coded offsets for certain characters:
https://github.com/id-Software/DOOM/blob/a77dfb96cb91780ca334d0d4cfd86957558007e0/linuxdoom-1.10/hu_lib.c#L100

**Comment by 72hr** [comment]
Ah... I see that it's just using the patch offsets everywhere. That keeps things simple. I set useOffset and removed alignment overrides on all the font definitions, and removed the BaseHeight functionality since it no longer has a reason to be added. If this looks OK, I'll create a PR. And if you have a list of other WADs to check I can run through them here and in other ports and verify.
