### ISSUE TITLE
"Bunny scroll" offset at end of E3M8 looks strange

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#621]
I'm not sure how this one should best be handled, but figured I'd point it out anyway since @72hr has been playing around with a bunch of intermission and endgame screen stuff.

The E3M8 endgame "bunny" graphic should probably be clipped based on what part is supposed to be visible, and then that part should probably be displayed in the center of the screen.  The current behavior just seems..odd.

(My display is 1920 x 1080)

As-is, it starts out like this:
![helion_20240823_07 39 42 2403](https://github.com/user-attachments/assets/b539f8c4-b960-42f6-ac7b-b3fb9cb66e1d)

And then at the end of the scroll, it looks like this:
![helion_20240823_07 39 56 4959](https://github.com/user-attachments/assets/0fef93d0-22dc-402a-93ad-185cfd69bdf8)

**Comment by 72hr** [comment]
The line

https://github.com/Helion-Engine/Helion/blob/4016bc591a2925758e85055d8cc6f61277e4e3e0/Core/Layer/EndGame/EndGameLayer.Render.cs#L43

can be changed to 

```csharp
m_theEndOffset = new Vec2I(-2 - handle.Dimension.Width / 2, -2 - handle.Dimension.Height / 2);
```

to at least fix the centering. See comparisons with a Dosbox Youtube video below. The END# sprites grow down and right, so they need to remain anchored top-left.

I agree that it makes sense to restrain the render area to its original intent, although I'm curious if PWADs have made use of this?

![end](https://github.com/user-attachments/assets/cc7a2c51-c4e4-489a-9d20-5f673d6a305a)
![helion_20240823_11 24 44 0354](https://github.com/user-attachments/assets/fadc22ac-1510-44eb-bbee-ab450067cac6)
![helion_20240823_11 24 55 8433](https://github.com/user-attachments/assets/e5655de1-e4aa-49e4-b9ad-fb67c293f9e2)

**Comment by 72hr** [comment]
I don't see a way to clip when drawing an image, so perhaps we could draw black boxes on top? Something like this:

![boxes](https://github.com/user-attachments/assets/26481451-b1da-4e3b-a206-656156cf08ef)

**Comment by lemming104** [comment]
I think that'll be good enough for now.

Hopefully we don't _next_ get to contend with cases where someone's made an ultrawide version.  😆
