### ISSUE TITLE
Transparency rendering quirk with hanging vines in Vanguard MAP02

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#628]
This only seems to happen in the true-color renderer, not in the palette renderer.
WAD:  Vanguard [here](https://www.dropbox.com/scl/fi/328giqbmcrhn0ha0tjujg/Vanguard-umapinfo-2.wad?rlkey=720yond1yurdkc9aqz13ystvx&st=glqfzbgy&dl=0)

There are some hanging vines all over MAP02.  You can sometimes see through them, through the ceilings above, and into the sky.  It looks kinda weird in motion.

https://github.com/user-attachments/assets/9e5ea72c-a44c-4d1c-8bfe-10190e758ea4

**Comment by lemming104** [comment]
Also only seems to happen when the vanilla-style sprite rendering feature is turned OFF.

**Comment by nstlaurent** [comment]
https://github.com/Helion-Engine/Helion/commit/c33ccc4054fe0990433b9944a1977a8112188134 should fix it
