### ISSUE TITLE
Ancient Aliens (all versions 1.0 - 1.3UMAPINFO), can fall through hole in MAP09

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#629]
In MAP09 of Ancient Aliens (any version), there's a bug where the player can fall into a pit and cannot escape.

As far as I can tell, this is actually a sort of monster closet--a hidden elevator filled with enemies.  It is supposed to raise when the player crosses some line on the map, probably as they climb the staircase necessary to reach this area from the starting area.

I checked both DSDA-Doom and GZDoom, and in both, this trap has been triggered by the time the player reaches this area in the intended manner.  In Helion, this does not happen, so the player can easily fall in and become stuck.  This is _not_ a new bug in Helion; it has been present for at least several months as far as I can remember.

Pictures (with map coordinates):
![helion_20240824_08 43 40 2749](https://github.com/user-attachments/assets/14e00986-e8a2-4d1c-9949-d476b1ea397d)
![helion_20240824_08 43 53 3525](https://github.com/user-attachments/assets/80651221-96b8-4913-a232-10b2d9f20f77)

**Comment by nstlaurent** [comment]
That's interesting. This is the trigger here. I didn't play the entire map but I put myself behind the line and it worked.

![image](https://github.com/user-attachments/assets/661cb922-6f3e-42d1-84fb-5e62c461f1e9)

**Comment by lemming104** [comment]
I just played around with it a bit more.  It is influenced by two things:
1.  Whether the monsters on the lift are still alive
2.  The "infinitely tall things" compatibility setting

If the monsters on the lift are alive at the time you cross the trigger line, then the elevator only works if they are infinitely tall.  If the monsters are already dead when you cross the trigger line (because you've used a console command to kill everything), then the elevator will always work.

**Comment by lemming104** [comment]
Intended fix is in 04df635cf326c32525792adf8cd7f6b0d9aa27d4
