### ISSUE TITLE
Pirate Doom 2: tree sprites change once MAP06 is ready

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#638]
present in 0.9.4 and in dev

https://github.com/user-attachments/assets/d4edfaa6-0172-4d03-a921-1cf67921b04f

**Comment by lemming104** [comment]
I don't know if it's the same issue, but I spotted something similar in SmoothDoom21.  There's a corpse within the player's line of sight right at the beginning of E1M1 in the original doom, and if you _restart_ the level by using the `kill` console command, you can watch it blink into existence.  😆

**Comment by 72hr** [comment]
Based on them hitting A_RandomJump the first two ticks into the game and other ports experiencing similar issues to varying degrees, it looks like there is nothing to be done here.
