### ISSUE TITLE
Custom control mapping breaks console when in-game

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#650]
This one's really weird.  I use non-default keybindings when I play Helion, because I prefer arrow keys over WASD.  The console behaves erratically, but only in-game.  On the menu, it's fine.

Here's a video of what I'm talking about.  In this video, I have opened the console while playing MAP01 of Doom II, and I'm just going across the keyboard, pressing each alphabetical key, e.g. `qwertyuiop...`.  It seems like the `e` and `c` keys are getting interpreted as something that should clear a row.

https://github.com/user-attachments/assets/dd38331d-cfba-4a1a-8cb1-2b9a15e17c0f

Here is the keybinding section from my config file.
```
[keys]
Backtick = ["Console"]
One = ["WeaponSlot1"]
Two = ["WeaponSlot2"]
Three = ["WeaponSlot3"]
Four = ["WeaponSlot4"]
Five = ["WeaponSlot5"]
Six = ["WeaponSlot6"]
Seven = ["WeaponSlot7"]
Equals = ["HudIncrease"]
Minus = ["HudDecrease"]
F2 = ["Save"]
F3 = ["Load"]
F4 = ["OptionsMenu"]
Tab = ["Automap"]
Pause = ["Pause"]
F6 = ["QuickSave"]
Escape = ["Menu"]
MouseWheelUp = ["AutoMapIncrease", "PreviousWeapon"]
MouseWheelDown = ["AutoMapDecrease", "NextWeapon"]
Y = []
W = ["AutoMapUp"]
A = ["AutoMapLeft"]
S = ["AutoMapDown"]
D = ["AutoMapRight"]
Up = ["Forward"]
Down = ["Backward"]
Left = ["Left"]
Right = ["Right"]
ShiftLeft = []
ShiftRight = []
AltLeft = []
AltRight = []
Space = []
C = []
MouseLeft = ["Attack"]
ControlLeft = []
ControlRight = []
PrintScreen = []
F12 = ["Screenshot"]
E = []
Enter = ["Use"]
```

**Comment by lemming104** [comment]
The interesting part would have to be those empty key bindings for C and E.  How did _those_ get there?

**Comment by lemming104** [comment]
Hmm, if I am on the menu and I use DEL to unmap a command (say, unmapping C from the un-implemented "crouch") it leaves empty-set assignments like `C = []`.

**Comment by 72hr** [comment]
I noticed 
```
AltLeft = ["Strafe"]
AltRight = ["Strafe"]
```
 always gets added back to the config if you remove it
