### ISSUE TITLE
pressing screenshot key advances intermission/textscreen/endgame and screenshot is taken late

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#652]
Mine is bound to F12. When I press this to capture one of these screens, the game advances and the screenshot is of the next rendered frame.

**Comment by lemming104** [comment]
Although it's not a complete fix for all input processing issues, I think it would make sense to restrict the intermission, text, and endgame screens so they only advance in response to Use and Fire.

I'll look into that.

**Comment by lemming104** [comment]
Should be fixed with that PR.
