### ISSUE TITLE
Godless Night doesn't work on Helion (Arch Linux)

### ISSUE THREAD

**Issue by aboutafter** [Helion-Engine/Helion#655]
Sorry if I'm screwing up and this mod should not work with Helion. I just wanted to try it on it because I have very poor performance on GZDoom and Helion would be the perfect way to play it. 

https://www.doomworld.com/forum/topic/141009-godless-night-gzdoom-episode-rc1-11292023/

I tried with version 0.9.4.0 and 0.9.5.0. 

> $ ./Helion godnite_rc1.pk3 
Helion v0.9.4.0 
Processor:  X64 
Processors: 12 
OS: Unix 6.10.6.1 x64 (running x64) 
CheckOpenGLSupport 45 
OpenGL v4.6 
OpenGL Shading Language: 4.60 
OpenGL Vendor: AMD 
OpenGL Hardware: AMD Radeon RX 6600 (radeonsi, navi23, LLVM 18.1.8, DRM 3.57, 6.10.6-arch1-1) 
OpenGL Extensions: 241 
GL_ARB_clip_control True 
MapPersistentBit True 
Unknown flag 'CLIENTSIDEONLY' for actor TangoSnowSpawner 
Parsing error: Expected text, got a 'Minus' instead 
Error parsing text on line 56, offset 54. Expected text, got a 'Minus' instead 
                TNT1 A 8 A_SpawnItemEx ("TangoSnowParticle", Random(-64, -64), Random(-64, -64), 0, frandom(-1.0, 1.0), frandom(-1.0, 1.0), frandom(-1.0, -3.0), 0, 128, 90) 
                                                      ^ 
Parsing error: Failed to parse include path at actors/Snow.dec 
Error parsing text on line 8, offset 1. Failed to parse include path at actors/Snow.dec 
#include "actors/Snow.dec" 
 ^ 
Error parsing text on line 19, offset 21. Hit end of file when expecting data. 
Error parsing text on line 3, offset 9. Invalid texture item: Graphic 
// Texture definitions generated by SLADE3 
^ 
Error parsing text on line 140, offset 0. SoundInfo - Bad command. $Limit 
DRYFIRE DRYFIRE 
^ 
Error parsing text on line 4, offset 13. Could not parse FireballSpitter/Flight as a double. 
Error parsing text on line 59, offset 0. Unknown animdefs type 0.2 
flat RATER1 
^ 
MapInfo: Unknown gameinfo item: playerclasses line:2 
MapInfo: Unknown section Automap 
MapInfo: Unknown gameinfo item: menufontcolor_title line:36 
MapInfo: Unknown gameinfo item: menufontcolor_label line:37 
MapInfo: Unknown gameinfo item: menufontcolor_value line:38 
MapInfo: Unknown gameinfo item: menufontcolor_action line:39 
MapInfo: Unknown gameinfo item: menufontcolor_header line:40 
MapInfo: Unknown gameinfo item: menufontcolor_highlight line:41 
MapInfo: Unknown gameinfo item: menufontcolor_selection line:42 
MapInfo: Unknown gameinfo item: menuslidercolor line:43 
MapInfo: Unknown gameinfo item: dimcolor line:44 
MapInfo: Unknown gameinfo item: dimamount line:45 
MapInfo: Unknown skill item: TextColor line:64 
MapInfo: Unknown skill item: = line:65 
MapInfo: Unknown skill item: = line:66 
MapInfo: Unknown skill item: = line:67 
MapInfo: Unknown skill item: = line:68 
MapInfo: Unknown skill item: = line:69 
MapInfo: Unknown skill item: = line:70 
MapInfo: Unknown skill item: = line:71 
MapInfo: Unknown skill item: = line:72 
MapInfo: Unknown skill item: = line:73 
MapInfo: Unknown skill item: = line:74 
MapInfo: Unknown skill item: = line:75 
MapInfo: Unknown skill item: TextColor line:87 
MapInfo: Unknown skill item: TextColor line:98 
MapInfo: Unknown skill item: TextColor line:109 
MapInfo: Unknown skill item: TextColor line:120 
MapInfo: Unknown skill item: TextColor line:132 
MapInfo: Unknown episode item: noskillmenu line:166 
Error parsing text on line 33, offset 23. Hit end of file when expecting data. 
Error parsing text on line 33, offset 17. Hit end of file when expecting data. 
Parsing error: Expected text, got a 'Period' instead 
Error parsing text on line 256, offset 29. Expected text, got a 'Period' instead 
                TNT1 A 0 A_SetBlend("Red", .25, 35) 
                             ^ 
Parsing error: Expected text, got a 'Minus' instead 
Error parsing text on line 145, offset 26. Expected text, got a 'Minus' instead 
         TNT1 A 0 ThrustThingZ(0,-2,0,1) 
                          ^ 
Error parsing text on line 3, offset 0. SoundInfo - Bad command. $Limit 
CRWFLP CRWFLP 
^ 
fluidsynth: warning: Requested audio-channels to high. Limiting this setting to audio-groups.
fluidsynth: warning: Failed to set thread to high priority
Cannot load map 'map01', it cannot be found or is corrupt 
Failed to load map 
Segmentation fault (core dumped)

If this mod can't run on Helion and it's not a bug, sorry!

**Comment by lemming104** [comment]
I'll let @nstlaurent reply in more detail if he likes before closing this, but this appears to use features that Helion does not support, including both ACS and ZScript.

Helion is roughly at parity with ports like DSDA-Doom in terms of what it supports--Boom and MBF mapping features, DeHackEd, and a few bits and pieces of DECORATE needed to support the MBF21 standard.  Support for the id24 mapping standard is Coming Soon™.

Helion _does not_ support the full set of GZDoom mapping features like 3D floors and slopes, does not have full support for DECORATE, and does not support ZScript.  I believe it also does not support Hexen features like hubs, polyobjects, and ACS.

**Comment by nstlaurent** [comment]
Indeed, Helion does not have the level of decorate support or ACS/ZScript required for GZDoom mods.
