### ISSUE TITLE
keys bound to console commands are consumed while the console is open

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#660]
On f084afc
With the binding `P = ["fly", "noclip"]`, when I have the console open and type P, the commands are executed and the current line is cleared

**Comment by lemming104** [comment]
I'll investigate this because I'm interested to see how stuff is currently routed and which layer gets precedence.

**Comment by lemming104** [comment]
I still want to do more work on input routing and precedence, but that should mitigate the immediate issue.
