### ISSUE TITLE
Separate "menu scale" from HUD scale

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#668]
Currently, the HUD scale setting also impacts text in menus.  I would prefer to have these as two separate things.  The menus currently remain pretty readable at smaller text sizes, but the HUD, particularly the stats in the upper right, turns into an eye chart rather quickly.

In my ideal world, I would play with the HUD elements fairly large (say, scale 2.0 at full-screen, 1920x1080), but with the options menus around scale 1.5 in the current system.

**Comment by 72hr** [comment]
I'm wondering if it makes sense to shift the scaling values so that 1 = draw bitmap fonts 1:1, (8px in places where we don't care about being 1:1), and then change the autoscaling so that the default is more like 3-4

**Comment by lemming104** [comment]
I'm not sold on any one particular solution, and I think we should feel free to prototype all kinds of different possibilities.  At any given HUD scale, the menu text currently displays _much_ larger than the pickup/status messages in-game, and I think they should either display at the same scale, or that it should be the other way around, since it is harder to focus and read when there are a lot of things happening on screen.

**Comment by lemming104** [comment]
#686
