### ISSUE TITLE
Reuse autosave files

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#672]
We should rotate through autosaves rather than flooding the save directory.  Whether this should be a "global" thing, or a "this combination of IWAD + PWADs" thing, I am unsure.

**Comment by 72hr** [comment]
Rotating quicksaves (instead of quicksaving over the last saved file) would be nice too

**Comment by lemming104** [comment]
I agree.

**Comment by 72hr** [comment]
Completed with #700
