### ISSUE TITLE
Fix or replace music playback layer

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#673]
This is a fairly major feature, but one we will probably need to undertake.

1. The NFluidSynth wrapper is...not great, and I keep finding new ways to crash Helion with it.
2. NAudio, which we use for OGG and MP3 playback, only works with WinMM as far as I know.  So, no Linux/Mac support.
3. We have no solution for playing back module files, and this at least used to be part of the id24 draft spec (don't know if it's still there).

We can either deal with these three problems independently, or tear out the whole music stack and try to wrap ZMusic.

**Comment by lemming104** [comment]
We have ZMusic now.

**Comment by PoorPocketsMcNewHold** [comment]
OGG and MP3 playback still doesn't work on a locally compiled dev branch Linux native build. Expected? Does the project come with Windows only ZMusic binary blobs? Did perhaps the ZMusic build broke for me?
I could create a separate issue if needed.
