### ISSUE TITLE
save files can't be loaded if they have a space in the filename

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#694]

**Comment by lemming104** [comment]
Since Helion always just generates its own filenames, I assume this is when there's a space somewhere else along the path, like the parent directory name?

**Comment by 72hr** [comment]
For this one I had renamed the file, so it's not something that's likely to be encountered. But looking into it briefly, it's because the loading is wrapping the console command. It seems you can quote args passed to console commands, so that's probably the fix. There's also a command line arg to load games that might be affected.
