### ISSUE TITLE
Berserk bug? 

### ISSUE THREAD

**Issue by syyyynapse** [Helion-Engine/Helion#760]
Odd bug concerning berserk, found in Thatchers Tech Base and Thatchers Tech Base exclusively. 

Picking up Berserk in Helion (9.4.0)
https://github.com/user-attachments/assets/f2bc412e-1a2b-4d3d-832c-863c6cadb579

Picking up Berkserk in DSDA-DOOM (0.28.1)
https://github.com/user-attachments/assets/dc15bb66-b767-4609-bd1e-4ec030406193

**Comment by nstlaurent** [comment]
This wad modified the red palette. This will only work in palette color mode. Options -> Video and change Color Mode to Palette.

**Comment by syyyynapse** [comment]
> This wad modified the red palette. This will only work in palette color mode. Options -> Video and change Color Mode to Palette.

Appreciate the response, not my issue though, my report is concerning the health value being unchanged.
