### ISSUE TITLE
Eviternity II -- holes in floor on MAP05

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#780]
This is probably another dup of the floor rendering issues reported elsewhere, but just in case.

Using [Eviternity II](https://eviternity.dfdoom.com/), final version (which came out the other day), load the attached saved game.
[savegame9.zip](https://github.com/user-attachments/files/17254832/savegame9.zip)  Press the switch immediately in front of you, then ride the elevator up.
![helion_20241004_12 28 54 4477](https://github.com/user-attachments/assets/9ddf063f-d32d-4161-9fc5-bd90d1f2a541)

**Comment by nstlaurent** [comment]
This is different. The closet that triggers the floors to raise changes their texture. Somehow those flats are being serialized incorrectly and or loaded incorrectly. Since it's a wall texture I suspect it's related to the id24 changes.
