### ISSUE TITLE
Clicking/popping when using high-quality sound effect replacements

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#801]
From https://www.doomworld.com/forum/post/2860153

```
 there a two things I wanna ask though. I usually load up the "Doom Sound Bulb" mod (which replaces the original sound effects with higher quality ones). while it works with other vanilla orientated source ports just fine (like Woof or dsda-doom), with Helion it causes audio crackles. I guess it's because the sound files are in 16bit rather than 8bit? the mod also has a legacy version with 8bit versions, which work without any issues with Helion.

https://www.moddb.com/mods/brutal-doom/addons/doom-sound-bulb-20-high-quality-sound-pack 
```
I tried this WAD, and it sounds like it's either overdriving and clipping a little, or there's some junk at the beginning or end of looping sound effects--this is particularly noticeable in the "idle" sound on the chainsaw.

**Comment by sinshu** [comment]
I tried to fix this in my branch:
https://github.com/sinshu/Helion/commit/6334ac3e3669bceb874b57ea8550724a163f0fbc

The chainsaw's idle sound seems to have improved with this fix. If it's okay to submit a PR, I’d like to submit this fix.

**Comment by nstlaurent** [comment]
@sinshu of course! Please do.
