### ISSUE TITLE
PS4 controller not working with Helion 0.9.5.0

### ISSUE THREAD

**Issue by JustinWayland** [Helion-Engine/Helion#804]
I heard that Helion had gotten support for controllers and raced over to try them out.  Unfortunately, it does not appear to work with PS4 controllers, at least on Linux.

XBox controller I had lying around worked fine though.

Might be an upstream issue with OpenTK.

Edit: Would be fine with this being done after Helion 0.9.5.0's release. I have Steam Input to force what I want onto Helion.

**Comment by lemming104** [comment]
We're unfortunately limited to what OpenTK tells us.  There's no controller-specific handling; we just grab the first controller it tells us about, if one is present, and everything beyond that is abstracted away from us.

I'll take a look at this later and see if there's any evidence at all that OpenTK is even notifying us when a PS4 controller is connected on a Linux environment.  One of our contributors has tried that type of controller on Windows, and it apparently just works there; go figure.

**Comment by JustinWayland** [comment]
I could see why it might: XBOX is listed under ```/dev/input/``` while the PS4 controller is under ```/dev/hidraw%i```.

**Comment by lemming104** [comment]
Is it completely inoperable, or are the default mappings just incorrect?  If the controller is detected, you _should_ be able to rebind its buttons and axes from the key binding menu when the main "use game controllers" option is turned on.

I know from earlier testing that the PS4 controller and XBOX controller may have different axis and button numbering.

The same contributor who previously tested with a PS4 controller says it seems to work on Arch, so there may also be some version or distribution issues here.

**Comment by JustinWayland** [comment]
The default mappings were incorrect.

**Comment by lemming104** [comment]
Ah, OK.  I feel better about that.  Those were a best effort based on the XBOX controller layout, and we knew those might be wrong for some controllers.  Post-0.9.5.0, we should probably add some default mappings based on other popular controllers.

**Comment by lemming104** [comment]
Logged https://github.com/Helion-Engine/Helion/issues/805 to track that potential improvement.
