### ISSUE TITLE
Gyro button needs to be implemented

### ISSUE THREAD

**Issue by JustinWayland** [Helion-Engine/Helion#883]
While I found gyro on Linux to be broken at the moment, a look through the controls enabled me to spot this critical oversight.

A gyro button, when pressed, either enables or disables gyro while it is held down.  Both options have their uses:

- If the gyro button enables gyro, this allows a player new to gyro to decide when to turn it on to aim, and use a more traditional control scheme to navigate the level.
- If the gyro button disables gyro, this allows a player to turn off the gyro to re-orient their controller into a more comfortable position. This is essential for longer play sessions to avoid wrist injuries.

If this has already been implemented, please point me to the entry in the replies.

**Comment by lemming104** [comment]
It's not implemented at the moment.  You should be able to use the thumbstick to reorient, though.

**Comment by lemming104** [comment]
https://github.com/Helion-Engine/Helion/pull/894
