### ISSUE TITLE
Gyro controls do not respect mouse look settings (UI/UX issue)

### ISSUE THREAD

**Issue by JustinWayland** [Helion-Engine/Helion#885]
When I got gyro aim working on Linux, I found out that gyro aiming will move your view up and down, even if you tried to turn it off by disabling mouse look.

This is mostly likely by design, but it's a nasty gotcha for the purists.

A workaround is to set the vertical sensitivity to 0 in the controller settings.

**Comment by lemming104** [comment]
I'm not 100% certain how this should work from a UX point of view.  When I was working on the SDL2 stuff, I bound the right thumbstick vertical axis to look up/down by default, and I set gyro aiming to full freelook.  It's possible to disable the vertical stuff by unbinding the thumbstick and setting gyro vertical sensitivity to zero, as you mention.

I'm not really sure, from a UX point of view, whether:
1. Thumbstick and gyro vertical aiming should respect mlook settings, OR
2. Thumbstick and gyro vertical aiming should be tied together and ignore mlook settings, OR
3. All three should be separate

**Comment by JustinWayland** [comment]
I personally feel like all three should be tied together in some singular compatibility setting.  I think if a player disables vertical mouselook, then often they want to disable the ability to look up and down altogether.

But I have learned long ago that just because I want that doesn't mean others want it.  I think we need some sort of survey.
