### ISSUE TITLE
Full status bar looks different than other ports

### ISSUE THREAD

**Issue by JustinWayland** [Helion-Engine/Helion#914]
![Screenshot_20241212_200234](https://github.com/user-attachments/assets/e6f52442-7d8a-4f79-8f72-056eefd50f87)

In particular the backgrounds to the left and right look very different to what is on other source ports

**Comment by nstlaurent** [comment]
Looks like the default background texture was changed to something that only exists in Doom 2. Will have to change that. You can change it in the options menu Hud -> Status Bar Texture.
